export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES';
export const GET_COUNTRIES_NAME = 'GET_COUNTRIES_NAME';
export const GET_COUNTRIES_ID = 'GET_COUNTRIES_ID';
export const CLEAR_DETAIL = 'CLEAR_DETAIL';